### ISSUE TITLE
Question about number representation and heap.

### ISSUE THREAD

**Issue by alinghi** [KAIST-IS521/backdoor-alinghi#1]
1. Immediate는 Simple number representation이라고 적혀있는데
: 8bit : 0xFF는 255로 0x80은 128로 0x00은 0으로 해석하면 되나요?(simple addition of each digit)

2. Heap이 8192까지 address가 있다고 하셨는데
Heap의 어드레스 한개당 32bit가 assign되나요?
총 heap의 용량은 8192*32bit=262144 bit이 되는건가요?

3. Register는 32bit인데 32bit의 숫자표현은 Two's complement인가요?

**Comment by sangkilc** [comment]
1. 네
2. 힙 주소는 0 에서 8192입니다: 용량이 8k 입니다.
3. 지금 C로 짜는데 two's complement 얘기가 왜 나오는지 모르겠습니다. 그냥 32비트 숫자(int32_t or uint32_t) 입니다.

**Comment by sangkilc** [comment]
다음부터는 개인 리포에서 issue를 보내지 마시고 모든 사람이 볼 수 있게 2017-Spring 리포에서 질문을 하시기 바랍니다.

**Comment by alinghi** [comment]
다음부터는 질문 2017-Spring에서 하겠습니다. 감사합니다.
